#! /bin/sh

DIR=/home/pace/go/src/github.com/user/hello

SIZES_KBYTES='
16
32
64
128
256
512
1024
2048
'



rm -f bytes.dat string.dat

for kbytes in $SIZES_KBYTES
do
    echo ""
    echo "====="
    echo "try $kbytes kbytes"

    ./mkprog -s $DIR/hello.go $kbytes
    need=`./needed -v -C $DIR go build`

    echo "... got $need mbytes"

    if [ "$need" != "err" ]
    then
	echo "$kbytes $need" >> string.dat
    fi


    ./mkprog $DIR/hello.go $kbytes
    need=`./needed -v -C $DIR go build`

    echo "... got $need mbytes"

    if [ "$need" != "err" ]
    then
	echo "$kbytes $need" >> bytes.dat
    fi

done
	
gnuplot GPRC
